[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --force-reset --accept-data-loss", "node prisma/seed.js"]

[start]
cmd = "node index.js"
